version: '3.6'
services:
  app:
    build: .
    ports:
      - 3000:3000
    environment:
      - ACCESS_SECRET=${ACCESS_SECRET}
      - REFRESH_SECRET=${REFRESH_SECRET}
    depends_on:
      - db
    env_file:
      - env.docker-compose
    links:
      - db
      - redis
  db:
    image: postgres
    ports:
      - 5432
    env_file:
      - env.docker-compose
  redis:
    image: redis
